### PR TITLE
Change date of geophysical survey report and permit other report

### PR DESCRIPTION
**Pull request by DavidArmstrongGSQ**
Two changes to OpenFileDateConfig.json

Geophysical Survey Report Final changed to 2 years, 6 months, 1 day:
Permit Report Other - Changed from 5 years to confidential.

### CODE REVIEW

**Review by talebib — COMMENTED** [review]
@DavidArmstrongGSQ 
Are you intending to change "geophysical survey report-acquisition" OR "geophysical-survey-report-final"?

**Comment by DavidArmstrongGSQ** [comment]
> @DavidArmstrongGSQ
> Are you intending to change "geophysical survey report-acquisition" OR "geophysical-survey-report-final"?

Can confirm is geophysical-survey-report-final.

**Review by talebib — APPROVED** [review]
All good.

**Comment by DavidArmstrongGSQ** [comment]
Closed due to additional changes needed

**Pull request closed without merging**
