### PR TITLE
Update reportTemplates.json

### PR DESCRIPTION
**Pull request by KellyVance**
Please find updated report config JSON.

Once approved please leave unmerged. We will use the file in this branch for UAT.
Merge to occur once UAT is successful

### CODE REVIEW

**Review by Greenwoodmatthew — APPROVED** [review]
Looks fine to me, seems we were exlcuding some chars in previous version with the wrong direction / ?  If this is ok with Redhsift and SRA approves i am keen to test in UAT ASAP

Matt

**Review by talebib — APPROVED** [review]
All good. Thanks.

**Comment by KellyVance** [comment]
Hi All. With 2 approvals I am going to let SRA load this into UAT, I ask @katewd and @DavidArmstrongGSQ  to hold off approvals until we do UAT and can take those results into account.

**Review by DavidArmstrongGSQ — APPROVED** [review]
Looks fair

**Comment by KellyVance** [comment]
Closing this pull request. File subsequently updated for other updates.
Will contact Bishal directly and have him insert the correct regex based on our specification.

**Pull request closed without merging**
